import React,{useEffect,useMemo,useState}from 'react';
import {createRoot}from 'react-dom/client';
import './style.css';
import './garamond.css';
import './minimal-effects.css';
import './upper-taskbar.css';

const NAV=[['command','Command Center'],['line','Live Line'],['nodes','Nodes'],['alerts','Alerts']];
const API_URL=(import.meta.env.VITE_API_URL||'http://127.0.0.1:8000').replace(/\/$/,'');
const POLE_CONFIG=[
  {poleId:'POLE_01',nodeId:'NODE_01'}, {poleId:'POLE_02',nodeId:'NODE_01'}, {poleId:'POLE_03',nodeId:'NODE_01'},
  {poleId:'POLE_04',nodeId:'NODE_02'}, {poleId:'POLE_05',nodeId:'NODE_02'}, {poleId:'POLE_06',nodeId:'NODE_02'}
];
const NODE_CONFIG=['NODE_01','NODE_02'];
const JUNCTION_ID='JUNCTION_01';
const fmt=(v,s='—')=>v===undefined||v===null||v===''?s:Number.isFinite(Number(v))?Number(v).toFixed(1):v;
const relativeTime=value=>{if(!value)return '—';const seconds=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000));return Number.isFinite(seconds)?seconds<60?`${seconds} sec ago`:`${Math.floor(seconds/60)} min ago`:value};
const poleLabel=id=>id.replace('_',' ');
function normalize(payload){const source=Array.isArray(payload)?payload:payload?.nodes||payload?.data||payload?.sensors||[];return source.map((item,i)=>({id:String(item.device_id||item.node_id||item.id||`NODE_${String(i+1).padStart(2,'0')}`).toUpperCase(),voltage:item.voltage,current:item.current,power:item.power??(item.voltage!=null&&item.current!=null?Number(item.voltage)*Number(item.current):null),signal:item.signal_strength??item.signal??item.rssi,status:String(item.status||item.connection_status||'UNKNOWN').toUpperCase(),last:item.last_seen||item.last_received||item.updated_at||item.timestamp}));}
function useTelemetry(){const [nodes,setNodes]=useState([]),[summary,setSummary]=useState({}),[state,setState]=useState('connecting'),[lastFetch,setLastFetch]=useState('');useEffect(()=>{let alive=true;let timer;const poll=async()=>{try{const [health,nodesResponse,summaryResponse]=await Promise.all([fetch(`${API_URL}/api/health`),fetch(`${API_URL}/api/nodes`),fetch(`${API_URL}/api/dashboard/summary`)]);if(!health.ok||!nodesResponse.ok||!summaryResponse.ok)throw Error('API unavailable');const list=normalize(await nodesResponse.json()).filter(node=>NODE_CONFIG.includes(node.id));if(alive){setNodes(list);setSummary(await summaryResponse.json());setState(list.length?'live':'waiting');setLastFetch(new Date().toLocaleTimeString('en-GB'));}}catch{if(alive)setState('offline')}finally{timer=setTimeout(poll,Number(import.meta.env.VITE_POLL_INTERVAL_MS||2000))}};poll();return()=>{alive=false;clearTimeout(timer)}},[]);return{nodes,summary,state,lastFetch}}
function usePrototype(nodes,state){return useMemo(()=>{const byNode=Object.fromEntries(nodes.map(node=>[node.id,node]));const poles=POLE_CONFIG.map(config=>{const node=byNode[config.nodeId];const status=node?.status==='ONLINE'?'NORMAL':node?.status==='FAULT'?'FAULT':node?.status==='OFFLINE'||state==='offline'?'OFFLINE':'UNKNOWN';return {...config,...node,status};});const active=poles.filter(pole=>pole.status==='NORMAL').length;const offline=poles.filter(pole=>pole.status==='OFFLINE').length;const fault=poles.filter(pole=>pole.status==='FAULT').length;return {poles,byNode,active,offline,fault};},[nodes,state]);}
function PowerLine({prototype,large=false}){return <section className={'line-command '+(large?'line-large':'')}>{large&&<div className="line-heading"><span>LIVE LINE / PROTOTYPE GRID</span><small>1 RECEIVER JUNCTION · 2 ESP32 NODES · 6 ELECTRIC POLES</small></div>}<div className="prototype-lines"><div className="junction-source"><i/><div><b>{JUNCTION_ID.replace('_',' ')}</b><small>RECEIVING NODE 01 + NODE 02 TELEMETRY</small></div></div>{NODE_CONFIG.map(nodeId=>{const poles=prototype.poles.filter(pole=>pole.nodeId===nodeId);const node=prototype.byNode[nodeId];const nodeStatus=node?.status==='ONLINE'?'NORMAL':node?.status==='FAULT'?'FAULT':node?.status==='OFFLINE'?'OFFLINE':'UNKNOWN';return <div className="prototype-line" key={nodeId}><div className={'line-node node-source '+nodeStatus.toLowerCase()}><i/><span>{nodeId.replace('_',' ')}</span><small>{nodeStatus}</small></div>{poles.map(pole=><React.Fragment key={pole.poleId}><div className="line-link"/><div className={'line-node '+pole.status.toLowerCase()}><i/><span>{poleLabel(pole.poleId)}</span><small>{pole.status}</small></div></React.Fragment>)}</div>})}</div></section>}
function Telemetry({nodes,state,lastFetch}){const primary=nodes[0];const label=state==='live'?'LIVE ESP32 DATA':state==='offline'?'BACKEND OFFLINE':state==='connecting'?'CONNECTING TO GRID...':'WAITING FOR ESP32 DATA';return <section className="telemetry-section"><div className="section-title"><span>LIVE NODE TELEMETRY</span><b className={state}>{state==='live'?'● LIVE ESP32 DATA':label}</b></div><div className="telemetry-summary">{[['NODE',primary?.id?.replace('_',' ')||'—'],['VOLTAGE',primary?`${fmt(primary.voltage)} V`:'—'],['CURRENT',primary?`${fmt(primary.current)} A`:'—'],['POWER',primary?`${fmt(primary.power)} W`:'—'],['ESP32',state==='live'?'CONNECTED':'—'],['LAST UPDATE',primary?.last?relativeTime(primary.last):lastFetch||'—']].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><div className="table-wrap"><table><thead><tr><th>NODE</th><th>VOLTAGE</th><th>CURRENT</th><th>POWER</th><th>STATUS</th><th>SIGNAL</th><th>LAST UPDATE</th></tr></thead><tbody>{nodes.length?nodes.map(n=><tr key={n.id}><td>{n.id.replace('_',' ')}</td><td>{fmt(n.voltage)} V</td><td>{fmt(n.current)} A</td><td>{fmt(n.power)} W</td><td className={n.status==='ONLINE'?'online':'offline-text'}>{n.status}</td><td>{n.signal??'N/A'}</td><td>{relativeTime(n.last)}</td></tr>):<tr><td colSpan="7" className="empty-data">{label} — polling the FastAPI node feed every 2 seconds</td></tr>}</tbody></table></div></section>}
function Command({prototype,state}){const status=prototype.offline?'warning':'normal';const message=prototype.offline?'PROTOTYPE POLE STATUS REQUIRES ATTENTION':state==='live'?'SIX-POLE PROTOTYPE ONLINE':'AWAITING PROTOTYPE TELEMETRY';return <section className="home-command"><section className="overview-status"><div className={'status-pill '+status}><i/><span>{message}</span></div><p>1 RECEIVER JUNCTION · 6 TOTAL POLES · 2 ESP32 NODES · {prototype.active} ACTIVE · {prototype.fault} FAULT · {prototype.offline} OFFLINE</p></section><section className="command-brief"><span>VOLT SENTINEL / COMMAND CENTER</span><blockquote>“Continuous line awareness begins with a clear view of every connection.”</blockquote><p>System topology: <b>1 Receiver Junction</b> receives telemetry from <b>2 ESP32 Nodes</b> for <b>6 Electric Poles</b>. NODE 01 monitors POLE 01–03; NODE 02 monitors POLE 04–06.</p></section></section>}
function Nodes({prototype,nodes,state,lastFetch}){return <><section className="page-panel nodes-page"><div className="section-title"><span>PROTOTYPE POLE MONITORING</span><b className={state}>{state==='live'?'● LIVE':'ESP32 '+state.toUpperCase()}</b></div><div className="node-grid">{prototype.poles.map(pole=><article className={pole.status==='OFFLINE'?'offline':''} key={pole.poleId}><i/><b>{poleLabel(pole.poleId)}</b><small>{pole.status}</small><span>{pole.nodeId.replace('_',' ')} · {pole.last?relativeTime(pole.last):lastFetch||'WAITING FOR DATA'}</span><span>{pole.voltage!=null?`${fmt(pole.voltage)} V · ${fmt(pole.current)} A`:'NO NODE READING'}</span></article>)}</div></section><section className="page-panel node-relationship"><div className="section-title"><span>RECEIVER JUNCTION RELATIONSHIP</span><b>1 JUNCTION · 2 NODES · 6 POLES</b></div><div className="junction-overview"><b>{JUNCTION_ID.replace('_',' ')}</b><span>Receives telemetry from NODE 01 and NODE 02.</span></div><div className="node-grid node-grid-two">{NODE_CONFIG.map(nodeId=>{const node=prototype.byNode[nodeId];const linked=prototype.poles.filter(pole=>pole.nodeId===nodeId);return <article className={node?.status==='OFFLINE'?'offline':''} key={nodeId}><i/><b>{nodeId.replace('_',' ')}</b><small>{node?.status||'AWAITING DATA'}</small><span>{linked.map(pole=>poleLabel(pole.poleId)).join(' · ')}</span><span>{node?.last?relativeTime(node.last):lastFetch||'WAITING FOR DATA'}</span></article>})}</div></section><Telemetry nodes={nodes} state={state} lastFetch={lastFetch}/></>}
function Alerts({prototype,state,lastFetch}){const alerts=prototype.poles.filter(pole=>pole.status==='OFFLINE'||pole.status==='FAULT');return <section className="page-panel alerts-page"><div className="section-title"><span>ACTIVE ALERTS</span><b className={alerts.length?'warning':''}>{alerts.length?'FAULT MONITOR':'NO ACTIVE FAULTS'}</b></div>{alerts.length?<>{alerts.map(pole=><article className="alert-card" key={pole.poleId}><strong>{pole.status} / {poleLabel(pole.poleId)} · {pole.nodeId.replace('_',' ')}</strong><span>Communication or node status requires inspection.</span><div><small>STATUS</small><b>{pole.status}</b><small>TIME</small><b>{pole.last?relativeTime(pole.last):lastFetch||'AWAITING BACKEND EVENT'}</b><small>RECOMMENDED ACTION</small><b>CHECK {pole.nodeId.replace('_',' ')} CONNECTION</b></div></article>)}</>:<p className="empty-data">No offline or fault poles reported for the six-pole prototype.</p>}{state==='offline'&&<p className="backend-note">Backend is currently unreachable. Alerts will resume when the FastAPI service is available.</p>}</section>}
function App(){const [view,setView]=useState('command');const [clock,setClock]=useState('');const telemetry=useTelemetry();const prototype=usePrototype(telemetry.nodes,telemetry.state);useEffect(()=>{const id=setInterval(()=>setClock(new Date().toLocaleTimeString('en-GB')),1000);return()=>clearInterval(id)},[]);let page=view==='command'?<Command prototype={prototype} state={telemetry.state}/>:view==='line'?<section className="line-page"><div className="overview-status"><div className="status-pill normal"><i/><span>LIVE PROTOTYPE LINE INSPECTION</span></div><p>JUNCTION 01 ← NODE 01 → POLE 01 → POLE 02 → POLE 03 &nbsp; / &nbsp; JUNCTION 01 ← NODE 02 → POLE 04 → POLE 05 → POLE 06</p></div><PowerLine prototype={prototype} large/><Telemetry {...telemetry}/></section>:view==='nodes'?<Nodes prototype={prototype} {...telemetry}/>:<Alerts prototype={prototype} {...telemetry}/>;return <main className="sentinel app-shell"><video className="backdrop" autoPlay muted loop playsInline preload="auto"><source src="/background.mp4" type="video/mp4"/></video><div className="vignette"/><div className="scanlines"/><header className="topbar hud-line"><div className="brand"><span>VOLT SENTINEL</span></div><nav className="taskbar">{NAV.map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="toolbar-status"><div className={'live '+(telemetry.state==='offline'?'critical':'')}><i/> {telemetry.state==='live'?'SYSTEM LIVE':telemetry.state==='offline'?'BACKEND OFFLINE':'WAITING'}</div><div className="top-meta"><span>GRID <b>{prototype.offline?'ATTENTION':'NORMAL'}</b></span><span>TIME <b>{clock}</b></span></div></div></header><div className="view-content">{page}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
