import React,{useEffect,useMemo,useState}from 'react';
import {createRoot}from 'react-dom/client';
import './style.css';
import './garamond.css';
import './minimal-effects.css';
import './upper-taskbar.css';

const NAV=[['command','Command Center'],['line','Live Line'],['nodes','Nodes'],['alerts','Alerts']];
const API_URL=(import.meta.env.VITE_API_URL||'http://127.0.0.1:8000').replace(/\/$/,'');
const fmt=(v,s='—')=>v===undefined||v===null||v===''?s:Number.isFinite(Number(v))?Number(v).toFixed(1):v;
const relativeTime=value=>{if(!value)return '—';const seconds=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000));return Number.isFinite(seconds)?seconds<60?`${seconds} sec ago`:`${Math.floor(seconds/60)} min ago`:value};
const nodeNo=id=>String(id||'').match(/\d+/)?.[0]||'';
function normalize(payload){const source=Array.isArray(payload)?payload:payload?.nodes||payload?.data||payload?.sensors||[];return source.map((item,i)=>({id:item.device_id||item.node_id||item.id||`NODE_${String(i+1).padStart(2,'0')}`,voltage:item.voltage,current:item.current,power:item.power??(item.voltage!=null&&item.current!=null?Number(item.voltage)*Number(item.current):null),signal:item.signal_strength??item.signal??item.rssi,status:String(item.status||item.connection_status||'UNKNOWN').toUpperCase(),sensor:item.sensor_status||item.status,last:item.last_seen||item.last_received||item.updated_at||item.timestamp}));}
function useTelemetry(){const [nodes,setNodes]=useState([]),[summary,setSummary]=useState({}),[state,setState]=useState('connecting'),[lastFetch,setLastFetch]=useState('');useEffect(()=>{let alive=true;let timer;const poll=async()=>{try{const [health,nodesResponse,summaryResponse]=await Promise.all([fetch(`${API_URL}/api/health`),fetch(`${API_URL}/api/nodes`),fetch(`${API_URL}/api/dashboard/summary`)]);if(!health.ok||!nodesResponse.ok||!summaryResponse.ok)throw Error('API unavailable');const list=normalize(await nodesResponse.json());if(alive){setNodes(list);setSummary(await summaryResponse.json());setState(list.length?'live':'waiting');setLastFetch(new Date().toLocaleTimeString('en-GB'));}}catch{if(alive)setState('offline')}finally{timer=setTimeout(poll,Number(import.meta.env.VITE_POLL_INTERVAL_MS||2000))}};poll();return()=>{alive=false;clearTimeout(timer)}},[]);return{nodes,summary,state,lastFetch}}
function PowerLine({nodes,large=false}){const byNumber=useMemo(()=>Object.fromEntries(nodes.map(n=>[nodeNo(n.id),n])),[nodes]);const fault=useMemo(()=>{const ordered=[...nodes].sort((a,b)=>Number(nodeNo(a.id))-Number(nodeNo(b.id)));for(let i=1;i<ordered.length;i++)if(ordered[i-1].status==='ONLINE'&&ordered[i].status==='OFFLINE')return [Number(nodeNo(ordered[i-1].id)),Number(nodeNo(ordered[i].id))];return nodes.length?null:[15,16]},[nodes]);return <section className={'line-command '+(large?'line-large':'')}>{large&&<div className="line-heading"><span>LIVE LINE / EAST CORRIDOR</span><small>20 NODE MONITORING ARRAY</small></div>}<div className="power-line"><div className="wire wire-top"/><div className="wire wire-mid"/><div className="wire wire-low"/><div className="pulse pulse-one"/><div className="pulse pulse-two"/>{Array.from({length:20},(_,i)=>i+1).map(n=>{const data=byNumber[String(n)];const offline=data?data.status==='OFFLINE':nodes.length===0&&n>=16;const unknown=!data&&nodes.length>0;return <React.Fragment key={n}>{fault?.[1]===n&&<div className="fault-span active"><b>{String(fault[0]).padStart(2,'0')} — {String(fault[1]).padStart(2,'0')}</b><span>FAULT SPAN</span></div>}<div className={'line-node '+(offline?'offline ':'')+(unknown?'unknown ':'')+(fault?.includes(n)?'affected':'')}><i/><span>NODE {String(n).padStart(2,'0')}</span><small>{offline?'OFFLINE':unknown?'UNKNOWN':'ONLINE'}</small></div></React.Fragment>})}</div>{fault&&<div className="line-fault active"><i>⚠</i><span><b>FAULT SPAN</b> NODE {String(fault[0]).padStart(2,'0')} → NODE {String(fault[1]).padStart(2,'0')}</span></div>}</section>}
function Telemetry({nodes,state,lastFetch}){const primary=nodes[0];const label=state==='live'?'LIVE ESP32 DATA':state==='offline'?'BACKEND OFFLINE':state==='connecting'?'CONNECTING TO GRID...':'WAITING FOR ESP32 DATA';return <section className="telemetry-section"><div className="section-title"><span>LIVE SENSOR TELEMETRY</span><b className={state}>{state==='live'?'● LIVE ESP32 DATA':label}</b></div><div className="telemetry-summary">{[['NODE',primary?.id||'—'],['VOLTAGE',primary?`${fmt(primary.voltage)} V`:'—'],['CURRENT',primary?`${fmt(primary.current)} A`:'—'],['POWER',primary?`${fmt(primary.power)} W`:'—'],['ESP32',state==='live'?'CONNECTED':'—'],['LAST UPDATE',primary?.last?relativeTime(primary.last):lastFetch||'—']].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><div className="table-wrap"><table><thead><tr><th>NODE</th><th>VOLTAGE</th><th>CURRENT</th><th>POWER</th><th>STATUS</th><th>SIGNAL</th><th>LAST UPDATE</th></tr></thead><tbody>{nodes.length?nodes.map(n=><tr key={n.id}><td>{n.id}</td><td>{fmt(n.voltage)} V</td><td>{fmt(n.current)} A</td><td>{fmt(n.power)} W</td><td className={n.status==='ONLINE'?'online':'offline-text'}>{n.status}</td><td>{n.signal??'N/A'}</td><td>{relativeTime(n.last)}</td></tr>):<tr><td colSpan="7" className="empty-data">{label} — polling the FastAPI node feed every 2 seconds</td></tr>}</tbody></table></div></section>}
function Command({nodes}){const online=nodes.length?nodes.filter(n=>n.status==='ONLINE').length:15;return <section className="home-command"><section className="overview-status"><div className="status-pill warning"><i/><span>FAULT SPAN UNDER INVESTIGATION</span></div><p>{online} / 20 NODES ONLINE · SUSPECTED SPAN NODE 15 → NODE 16</p></section><section className="command-brief"><span>VOLT SENTINEL / COMMAND CENTER</span><blockquote>“Continuous line awareness begins with a clear view of every connection.”</blockquote><p>VOLT SENTINEL monitors voltage, current, communication health, and fault transitions across the overhead network. Select <b>Live Line</b>, <b>Nodes</b>, or <b>Alerts</b> to activate detailed operational data.</p></section></section>}
function Nodes({nodes,state,lastFetch}){return <><section className="page-panel nodes-page"><div className="section-title"><span>NODE MONITORING</span><b className={state}>{state==='live'?'● LIVE':'ESP32 '+state.toUpperCase()}</b></div><div className="node-grid">{Array.from({length:20},(_,i)=>{const n=i+1;const data=nodes.find(x=>Number(nodeNo(x.id))===n);const offline=data?data.status!=='ONLINE':n>=16;return <article className={offline?'offline':''} key={n}><i/><b>NODE {String(n).padStart(2,'0')}</b><small>{offline?'OFFLINE / FAULT':'ONLINE / MONITORED'}</small><span>{data?.last||lastFetch||'WAITING FOR DATA'}</span></article>})}</div></section><Telemetry nodes={nodes} state={state} lastFetch={lastFetch}/></>}
function Alerts({state,lastFetch}){return <section className="page-panel alerts-page"><div className="section-title"><span>ACTIVE ALERTS</span><b className="warning">FAULT MONITOR</b></div><article className="alert-card"><strong>FAULT SPAN / NODE 15 → NODE 16</strong><span>Suspected wire break or communication loss</span><div><small>STATUS</small><b>INVESTIGATING</b><small>TIME</small><b>{lastFetch||'AWAITING BACKEND EVENT'}</b><small>RECOMMENDED ACTION</small><b>DISPATCH FIELD INSPECTION</b></div></article>{state==='offline'&&<p className="backend-note">Backend is currently unreachable. Alerts will resume when the FastAPI service is available.</p>}</section>}
function App(){const [view,setView]=useState('command');const [clock,setClock]=useState('');const telemetry=useTelemetry();useEffect(()=>{const id=setInterval(()=>setClock(new Date().toLocaleTimeString('en-GB')),1000);return()=>clearInterval(id)},[]);let page=view==='command'?<Command {...telemetry}/>:view==='line'?<section className="line-page"><div className="overview-status"><div className="status-pill warning"><i/><span>LIVE LINE INSPECTION</span></div><p>NODE 15 → NODE 16 / SUSPECTED AFFECTED SPAN</p></div><PowerLine nodes={telemetry.nodes} large/><Telemetry {...telemetry}/></section>:view==='nodes'?<Nodes {...telemetry}/>:<Alerts {...telemetry}/>;return <main className="sentinel app-shell"><video className="backdrop" autoPlay muted loop playsInline preload="auto"><source src="/background.mp4" type="video/mp4"/></video><div className="vignette"/><div className="scanlines"/><header className="topbar hud-line"><div className="brand"><span>VOLT SENTINEL</span></div><nav className="taskbar">{NAV.map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="toolbar-status"><div className={'live '+(telemetry.state==='offline'?'critical':'')}><i/> {telemetry.state==='live'?'SYSTEM LIVE':telemetry.state==='offline'?'BACKEND OFFLINE':'WAITING'}</div><div className="top-meta"><span>GRID <b>NORMAL</b></span><span>TIME <b>{clock}</b></span></div></div></header><div className="view-content">{page}</div></main>}
createRoot(document.getElementById('root')).render(<App/>);
